import json
from pathlib import Path

path = Path('molu_chat_0920.ipynb')
nb = json.loads(path.read_text(encoding='utf-8'))
cell = nb['cells'][11]
source = ''.join(cell['source'])
source = source.replace('"checkpoint_dir": "molu_chatbot"', '"checkpoint_dir": "molu_pretrain"')
source = source.replace('checkpoint_dir = Path(TRAIN_CFG["checkpoint_dir"])\n            checkpoint_dir.mkdir(parents=True, exist_ok=True)\n\n            torch.save(model.state_dict(), checkpoint_dir / "model.pt")\n\n            config_payload = {\n                "vocab_size": VOCAB_SIZE,\n                "d_model": 512,\n                "n_layers": 8,\n                "n_heads": 8,\n                "max_len": MAX_LEN,\n                "dropout": 0.1,\n                "special_tokens": {"PAD": PAD, "BOS": BOS, "SEP": SEP, "EOS": EOS},\n                "train_config": {**TRAIN_CFG, "betas": list(TRAIN_CFG["betas"])},\n                "best_val_loss": best_val,\n            }\n            with open(checkpoint_dir / "config.json", "w", encoding="utf-8") as f_cfg:\n                json.dump(config_payload, f_cfg, indent=2, ensure_ascii=False)\n            with open(checkpoint_dir / "metrics.json", "w", encoding="utf-8") as f_metrics:\n                json.dump(history, f_metrics, indent=2, ensure_ascii=False)\n\n            print(f"saved checkpoint to {checkpoint_dir.resolve()}")',
'checkpoint_dir = Path(TRAIN_CFG["checkpoint_dir"])\n            checkpoint_dir.mkdir(parents=True, exist_ok=True)\n\n            torch.save(model.state_dict(), checkpoint_dir / "model.pt")\n\n            config_payload = {\n                "vocab_size": VOCAB_SIZE,\n                "d_model": 512,\n                "n_layers": 8,\n                "n_heads": 8,\n                "max_len": MAX_LEN,\n                "dropout": 0.1,\n                "special_tokens": {"PAD": PAD, "BOS": BOS, "SEP": SEP, "EOS": EOS},\n                "train_config": {**TRAIN_CFG, "betas": list(TRAIN_CFG["betas"])},\n                "best_val_loss": best_val,\n            }\n            with open(checkpoint_dir / "config.json", "w", encoding="utf-8") as f_cfg:\n                json.dump(config_payload, f_cfg, indent=2, ensure_ascii=False)\n            with open(checkpoint_dir / "metrics.json", "w", encoding="utf-8") as f_metrics:\n                json.dump(history, f_metrics, indent=2, ensure_ascii=False)\n\n            print(f"saved checkpoint to {checkpoint_dir.resolve()}")')
cell['source'] = source.splitlines(keepends=True)
path.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding='utf-8')
